# Generated by Django 3.2.10 on 2021-12-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=50)),
                ('codigo_produto', models.IntegerField(max_length=10)),
                ('descricao_produto', models.CharField(blank=True, max_length=500)),
                ('preco_produto', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('img_produto', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('status_produto', models.CharField(choices=[('Disponivel', 'Disponivel'), ('Indisponivel', 'Indisponivel')], default=0, max_length=15)),
                ('idioma', models.CharField(choices=[('pt_BR', 'pt_BR'), ('en_US', 'en_US')], default=0, max_length=10)),
            ],
        ),
    ]
