# Generated by Django 2.0 on 2021-12-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=50)),
                ('codigo_produto', models.CharField(blank=True, max_length=10)),
                ('descricao_produto', models.CharField(blank=True, max_length=500)),
                ('preco_produto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('img_produto', models.FileField(blank=True, upload_to='produtos.images')),
                ('status_produto', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default=0, max_length=10)),
                ('idioma', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default=0, max_length=10)),
            ],
        ),
    ]
