# Generated by Django 3.2.10 on 2021-12-21 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria_produto',
            field=models.CharField(choices=[('Suco', 'Suco'), ('Hamburger', 'Hamburger'), ('Bebidas', 'Bebidas'), ('Pizza', 'Pizza')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_produto',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='img_produto',
            field=models.FileField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_produto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
