# Generated by Django 3.2.10 on 2021-12-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20211221_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria_produto',
        ),
    ]
