# Generated by Django 2.0 on 2021-12-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20211214_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='idioma',
            field=models.CharField(choices=[('pt_BR', 'pt_BR'), ('en_US', 'en_US')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='img_produto',
            field=models.ImageField(blank=True, upload_to='produtos.images'),
        ),
    ]
