# Generated by Django 2.0 on 2021-12-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_auto_20211214_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='img_produto',
            field=models.FileField(blank=True, null=True, upload_to='produtos.images/'),
        ),
    ]
