# Generated by Django 2.0 on 2021-12-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20211214_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='img_produto',
            field=models.ImageField(blank=True, null=True, upload_to='produtos.images/'),
        ),
    ]
