# Generated by Django 2.0 on 2021-12-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_auto_20211214_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='id',
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo_produto',
            field=models.AutoField(db_column='BID', primary_key=True, serialize=False),
        ),
    ]
