# Generated by Django 2.0 on 2021-12-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_auto_20211214_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='codigo_produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
