# Generated by Django 2.0 on 2021-12-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0009_auto_20211214_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='id',
        ),
        migrations.AddField(
            model_name='produto',
            name='codigo_produto',
            field=models.AutoField(db_column='BID', default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
