# Generated by Django 3.2.10 on 2021-12-15 18:17

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0002_auto_20211209_1554'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perfil_do_usuario',
            new_name='UserProfile',
        ),
    ]
